-- 为 MCP Server 增加认证模式，明确区分匿名、静态 Bearer 和 OAuth。
ALTER TABLE mcp_server
    ADD COLUMN auth_type VARCHAR(32);

UPDATE mcp_server
SET auth_type = CASE
                    WHEN credential_id IS NOT NULL THEN 'STATIC_BEARER'
                    ELSE 'NONE'
    END
WHERE auth_type IS NULL;

ALTER TABLE mcp_server
    ALTER COLUMN auth_type SET NOT NULL;

CREATE INDEX idx_mcp_server_auth_type ON mcp_server (auth_type);

-- MCP OAuth 连接：保存租户级别的 OAuth 授权状态、发现结果和可刷新的 token。
CREATE TABLE mcp_oauth_connection
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                    BIGINT       NOT NULL,
    server_id                    BIGINT       NOT NULL,
    connected_by_user_id         BIGINT       NOT NULL,
    status                       VARCHAR(32)  NOT NULL,
    resource_metadata_url        VARCHAR(1000),
    authorization_server_issuer  VARCHAR(1000),
    authorization_endpoint       VARCHAR(1000),
    token_endpoint               VARCHAR(1000),
    resource_indicator           VARCHAR(1000),
    client_id                    VARCHAR(255) NOT NULL,
    client_secret_ciphertext     TEXT,
    requested_scopes             VARCHAR(1000),
    granted_scopes               VARCHAR(1000),
    token_type                   VARCHAR(64),
    access_token_ciphertext      TEXT,
    refresh_token_ciphertext     TEXT,
    expires_at                   TIMESTAMPTZ,
    authorization_state          VARCHAR(255),
    authorization_expires_at     TIMESTAMPTZ,
    code_verifier_ciphertext     TEXT,
    last_error_code              VARCHAR(64),
    last_error_message           VARCHAR(1000),
    last_authorized_at           TIMESTAMPTZ,
    last_token_refreshed_at      TIMESTAMPTZ,
    created_at                   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_mcp_oauth_connection_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_mcp_oauth_connection_server FOREIGN KEY (server_id) REFERENCES mcp_server (id),
    CONSTRAINT fk_mcp_oauth_connection_user FOREIGN KEY (connected_by_user_id) REFERENCES app_user (id),
    CONSTRAINT uk_mcp_oauth_connection_server UNIQUE (server_id),
    CONSTRAINT uk_mcp_oauth_connection_state UNIQUE (authorization_state)
);

CREATE INDEX idx_mcp_oauth_connection_tenant_id ON mcp_oauth_connection (tenant_id);
CREATE INDEX idx_mcp_oauth_connection_server_id ON mcp_oauth_connection (server_id);
CREATE INDEX idx_mcp_oauth_connection_status ON mcp_oauth_connection (status);
