-- Agent 增加会话摘要记忆配置。
ALTER TABLE agent
    ADD COLUMN memory_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN memory_strategy VARCHAR(32),
    ADD COLUMN memory_update_message_threshold INTEGER NOT NULL DEFAULT 6;

CREATE INDEX idx_agent_memory_enabled ON agent (memory_enabled);
CREATE INDEX idx_agent_memory_strategy ON agent (memory_strategy);

-- 会话记忆表：保存每个会话的长期摘要记忆。
CREATE TABLE chat_session_memory
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                BIGINT       NOT NULL,
    session_id               BIGINT       NOT NULL,
    memory_type              VARCHAR(32)  NOT NULL,
    summary                  TEXT         NOT NULL,
    last_message_id          BIGINT,
    version                  INTEGER      NOT NULL DEFAULT 1,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_chat_session_memory_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_chat_session_memory_session FOREIGN KEY (session_id) REFERENCES chat_session (id),
    CONSTRAINT fk_chat_session_memory_last_message FOREIGN KEY (last_message_id) REFERENCES chat_message (id),
    CONSTRAINT uk_chat_session_memory_session_type UNIQUE (session_id, memory_type)
);

CREATE INDEX idx_chat_session_memory_tenant_id ON chat_session_memory (tenant_id);
CREATE INDEX idx_chat_session_memory_session_id ON chat_session_memory (session_id);
CREATE INDEX idx_chat_session_memory_last_message_id ON chat_session_memory (last_message_id);
