CREATE TABLE billing_account
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT        NOT NULL,
    balance    DECIMAL(18,6) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_billing_account_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT uk_billing_account_tenant UNIQUE (tenant_id)
);

CREATE INDEX idx_billing_account_tenant_id ON billing_account (tenant_id);

CREATE TABLE billing_transaction
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT        NOT NULL,
    account_id        BIGINT        NOT NULL,
    user_id           BIGINT,
    transaction_type  VARCHAR(32)   NOT NULL,
    amount_delta      DECIMAL(18,6) NOT NULL,
    balance_after     DECIMAL(18,6) NOT NULL,
    currency          VARCHAR(16)   NOT NULL,
    description       VARCHAR(512),
    model_call_log_id BIGINT,
    model_name        VARCHAR(128),
    credential_source VARCHAR(32),
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_billing_transaction_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_billing_transaction_account FOREIGN KEY (account_id) REFERENCES billing_account (id),
    CONSTRAINT fk_billing_transaction_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_billing_transaction_model_call_log FOREIGN KEY (model_call_log_id) REFERENCES model_call_log (id)
);

CREATE INDEX idx_billing_transaction_tenant_id ON billing_transaction (tenant_id);
CREATE INDEX idx_billing_transaction_account_id ON billing_transaction (account_id);
CREATE INDEX idx_billing_transaction_user_id ON billing_transaction (user_id);
CREATE INDEX idx_billing_transaction_model_call_log_id ON billing_transaction (model_call_log_id);
CREATE INDEX idx_billing_transaction_created_at ON billing_transaction (created_at DESC);
