CREATE TABLE official_model_credential
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(128) NOT NULL,
    provider          VARCHAR(32)  NOT NULL,
    base_url          VARCHAR(255) NOT NULL,
    secret_ciphertext VARCHAR(2048) NOT NULL,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_official_model_credential_name UNIQUE (name)
);

CREATE INDEX idx_official_model_credential_enabled ON official_model_credential (enabled);

CREATE TABLE official_model_config
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     VARCHAR(128)  NOT NULL,
    provider                 VARCHAR(32)   NOT NULL,
    model_type               VARCHAR(32)   NOT NULL,
    model_name               VARCHAR(128)  NOT NULL,
    official_credential_id   BIGINT        NOT NULL,
    temperature              DECIMAL(4,3),
    max_tokens               INTEGER,
    input_price_per_million  DECIMAL(18,6) NOT NULL DEFAULT 0,
    output_price_per_million DECIMAL(18,6) NOT NULL DEFAULT 0,
    currency                 VARCHAR(16)   NOT NULL,
    description              VARCHAR(512),
    enabled                  BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_official_model_config_credential FOREIGN KEY (official_credential_id) REFERENCES official_model_credential (id),
    CONSTRAINT uk_official_model_config_name UNIQUE (name)
);

CREATE INDEX idx_official_model_config_enabled ON official_model_config (enabled);
CREATE INDEX idx_official_model_config_model_type ON official_model_config (model_type);
