CREATE TABLE user_wallet
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT         NOT NULL,
    balance    DECIMAL(18, 6) NOT NULL DEFAULT 0,
    currency   VARCHAR(16)    NOT NULL,
    status     VARCHAR(32)    NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_user_wallet_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT uk_user_wallet_user_id UNIQUE (user_id)
);

CREATE INDEX idx_user_wallet_status ON user_wallet (status);

CREATE TABLE user_wallet_transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id        BIGINT         NOT NULL,
    user_id          BIGINT         NOT NULL,
    transaction_type VARCHAR(32)    NOT NULL,
    amount_delta     DECIMAL(18, 6) NOT NULL,
    balance_after    DECIMAL(18, 6) NOT NULL,
    currency         VARCHAR(16)    NOT NULL,
    reference_type   VARCHAR(32),
    reference_id     BIGINT,
    description      VARCHAR(512),
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_user_wallet_transaction_wallet FOREIGN KEY (wallet_id) REFERENCES user_wallet (id),
    CONSTRAINT fk_user_wallet_transaction_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX idx_user_wallet_transaction_user_id ON user_wallet_transaction (user_id, id DESC);
CREATE INDEX idx_user_wallet_transaction_reference ON user_wallet_transaction (reference_type, reference_id);

CREATE TABLE recharge_order
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT         NOT NULL,
    amount        DECIMAL(18, 6) NOT NULL,
    currency      VARCHAR(16)    NOT NULL,
    status        VARCHAR(32)    NOT NULL,
    remark        VARCHAR(512),
    reviewed_by   BIGINT,
    reviewed_at   TIMESTAMPTZ,
    review_remark VARCHAR(512),
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_recharge_order_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_recharge_order_reviewer FOREIGN KEY (reviewed_by) REFERENCES app_user (id)
);

CREATE INDEX idx_recharge_order_user_id ON recharge_order (user_id, id DESC);
CREATE INDEX idx_recharge_order_status ON recharge_order (status, id DESC);

CREATE TABLE billing_usage_event
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT         NOT NULL,
    tenant_id                BIGINT         NOT NULL,
    agent_id                 BIGINT         NOT NULL,
    session_id               BIGINT         NOT NULL,
    model_call_log_id        BIGINT         NOT NULL,
    official_model_config_id BIGINT         NOT NULL,
    model_name               VARCHAR(128)   NOT NULL,
    prompt_tokens            INTEGER,
    completion_tokens        INTEGER,
    input_price_per_million  DECIMAL(18, 6) NOT NULL,
    output_price_per_million DECIMAL(18, 6) NOT NULL,
    calculated_amount        DECIMAL(18, 6) NOT NULL,
    currency                 VARCHAR(16)    NOT NULL,
    status                   VARCHAR(32)    NOT NULL DEFAULT 'PENDING',
    processed_at             TIMESTAMPTZ,
    error_message            VARCHAR(1000),
    created_at               TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_billing_usage_event_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_billing_usage_event_model_call_log FOREIGN KEY (model_call_log_id) REFERENCES model_call_log (id),
    CONSTRAINT fk_billing_usage_event_official_model_config FOREIGN KEY (official_model_config_id) REFERENCES official_model_config (id),
    CONSTRAINT uk_billing_usage_event_model_call_log_id UNIQUE (model_call_log_id)
);

CREATE INDEX idx_billing_usage_event_status ON billing_usage_event (status, id ASC);
CREATE INDEX idx_billing_usage_event_user_id ON billing_usage_event (user_id, id DESC);
