CREATE TABLE market_asset
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type       VARCHAR(32)   NOT NULL,
    submitter_user_id BIGINT       NOT NULL,
    source_tenant_id BIGINT        NOT NULL,
    source_entity_id BIGINT        NOT NULL,
    name             VARCHAR(128)  NOT NULL,
    summary          VARCHAR(512),
    description      TEXT,
    snapshot_json    TEXT          NOT NULL,
    status           VARCHAR(32)   NOT NULL,
    reviewed_by      BIGINT,
    reviewed_at      TIMESTAMPTZ,
    review_remark    VARCHAR(512),
    published_at     TIMESTAMPTZ,
    install_count    INTEGER       NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_market_asset_submitter FOREIGN KEY (submitter_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_market_asset_reviewer FOREIGN KEY (reviewed_by) REFERENCES app_user (id),
    CONSTRAINT uk_market_asset_source UNIQUE (asset_type, source_tenant_id, source_entity_id)
);

CREATE INDEX idx_market_asset_status ON market_asset (status, published_at DESC, id DESC);
CREATE INDEX idx_market_asset_submitter ON market_asset (submitter_user_id, id DESC);
CREATE INDEX idx_market_asset_asset_type ON market_asset (asset_type, id DESC);

CREATE TABLE market_asset_install
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_asset_id   BIGINT        NOT NULL,
    installer_user_id BIGINT        NOT NULL,
    tenant_id         BIGINT        NOT NULL,
    installed_entity_id BIGINT      NOT NULL,
    installed_name    VARCHAR(128)  NOT NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_market_asset_install_asset FOREIGN KEY (market_asset_id) REFERENCES market_asset (id),
    CONSTRAINT fk_market_asset_install_user FOREIGN KEY (installer_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_market_asset_install_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id)
);

CREATE INDEX idx_market_asset_install_asset ON market_asset_install (market_asset_id, id DESC);
CREATE INDEX idx_market_asset_install_tenant ON market_asset_install (tenant_id, id DESC);
