-- 当前版本新增凭证表，用于保存用户自己的模型 API Key。
CREATE TABLE credential
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT       NOT NULL,
    name               VARCHAR(128) NOT NULL,
    provider           VARCHAR(32)  NOT NULL,
    credential_type    VARCHAR(32)  NOT NULL,
    secret_ciphertext  TEXT         NOT NULL,
    secret_masked      VARCHAR(255) NOT NULL,
    description        VARCHAR(512),
    status             VARCHAR(32)  NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_credential_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT uk_credential_user_name UNIQUE (user_id, name)
);

CREATE INDEX idx_credential_user_id ON credential (user_id);
CREATE INDEX idx_credential_provider ON credential (provider);
CREATE INDEX idx_credential_status ON credential (status);
