-- 模型配置表：租户下可复用的模型调用配置。
CREATE TABLE model_config
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT        NOT NULL,
    name           VARCHAR(128)  NOT NULL,
    provider       VARCHAR(32)   NOT NULL,
    model_type     VARCHAR(32)   NOT NULL,
    model_name     VARCHAR(128)  NOT NULL,
    credential_id  BIGINT,
    temperature    DECIMAL(4,3),
    max_tokens     INTEGER,
    enabled        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_model_config_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_model_config_credential FOREIGN KEY (credential_id) REFERENCES credential (id),
    CONSTRAINT uk_model_config_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX idx_model_config_tenant_id ON model_config (tenant_id);
CREATE INDEX idx_model_config_credential_id ON model_config (credential_id);
CREATE INDEX idx_model_config_provider ON model_config (provider);
CREATE INDEX idx_model_config_model_type ON model_config (model_type);
CREATE INDEX idx_model_config_enabled ON model_config (enabled);
