-- Agent 表：租户下可管理的智能体基础配置。
CREATE TABLE agent
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT        NOT NULL,
    name                VARCHAR(128)  NOT NULL,
    description         VARCHAR(512),
    system_prompt       TEXT          NOT NULL,
    model_config_id     BIGINT        NOT NULL,
    context_strategy    VARCHAR(32)   NOT NULL,
    context_window_size INTEGER       NOT NULL,
    enabled             BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_agent_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_agent_model_config FOREIGN KEY (model_config_id) REFERENCES model_config (id),
    CONSTRAINT uk_agent_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX idx_agent_tenant_id ON agent (tenant_id);
CREATE INDEX idx_agent_model_config_id ON agent (model_config_id);
CREATE INDEX idx_agent_context_strategy ON agent (context_strategy);
CREATE INDEX idx_agent_enabled ON agent (enabled);
