-- 聊天会话表：保存某个 Agent 下的一组对话容器。
CREATE TABLE chat_session
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT        NOT NULL,
    agent_id   BIGINT        NOT NULL,
    title      VARCHAR(128)  NOT NULL,
    created_by BIGINT        NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_chat_session_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_chat_session_agent FOREIGN KEY (agent_id) REFERENCES agent (id),
    CONSTRAINT fk_chat_session_created_by FOREIGN KEY (created_by) REFERENCES app_user (id)
);

CREATE INDEX idx_chat_session_tenant_id ON chat_session (tenant_id);
CREATE INDEX idx_chat_session_agent_id ON chat_session (agent_id);
CREATE INDEX idx_chat_session_created_by ON chat_session (created_by);
CREATE INDEX idx_chat_session_updated_at ON chat_session (updated_at DESC);

-- 聊天消息表：保存完整对话历史，滑动窗口会按消息时间倒序裁剪。
CREATE TABLE chat_message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT        NOT NULL,
    session_id BIGINT        NOT NULL,
    role       VARCHAR(32)   NOT NULL,
    content    TEXT          NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_chat_message_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_chat_message_session FOREIGN KEY (session_id) REFERENCES chat_session (id)
);

CREATE INDEX idx_chat_message_session_id ON chat_message (session_id);
CREATE INDEX idx_chat_message_tenant_id ON chat_message (tenant_id);
CREATE INDEX idx_chat_message_role ON chat_message (role);

-- 模型调用日志表：记录模型调用结果、耗时和密钥来源，便于后续审计。
CREATE TABLE model_call_log
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT        NOT NULL,
    user_id           BIGINT        NOT NULL,
    agent_id          BIGINT        NOT NULL,
    session_id        BIGINT        NOT NULL,
    user_message_id   BIGINT        NOT NULL,
    provider          VARCHAR(32)   NOT NULL,
    model_name        VARCHAR(128)  NOT NULL,
    credential_source VARCHAR(32)   NOT NULL,
    credential_id     BIGINT,
    status            VARCHAR(32)   NOT NULL,
    latency_ms        BIGINT,
    prompt_tokens     INTEGER,
    completion_tokens INTEGER,
    total_tokens      INTEGER,
    error_code        VARCHAR(64),
    error_message     VARCHAR(1000),
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_model_call_log_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_model_call_log_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_model_call_log_agent FOREIGN KEY (agent_id) REFERENCES agent (id),
    CONSTRAINT fk_model_call_log_session FOREIGN KEY (session_id) REFERENCES chat_session (id),
    CONSTRAINT fk_model_call_log_user_message FOREIGN KEY (user_message_id) REFERENCES chat_message (id),
    CONSTRAINT fk_model_call_log_credential FOREIGN KEY (credential_id) REFERENCES credential (id)
);

CREATE INDEX idx_model_call_log_tenant_id ON model_call_log (tenant_id);
CREATE INDEX idx_model_call_log_user_id ON model_call_log (user_id);
CREATE INDEX idx_model_call_log_agent_id ON model_call_log (agent_id);
CREATE INDEX idx_model_call_log_session_id ON model_call_log (session_id);
CREATE INDEX idx_model_call_log_status ON model_call_log (status);
CREATE INDEX idx_model_call_log_created_at ON model_call_log (created_at DESC);
