-- 知识库表：租户下可绑定到 Agent 的单知识库配置。
CREATE TABLE knowledge_base
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                 BIGINT        NOT NULL,
    name                      VARCHAR(128)  NOT NULL,
    description               VARCHAR(512),
    embedding_model_config_id BIGINT        NOT NULL,
    enabled                   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at                TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_knowledge_base_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_knowledge_base_embedding_model_config FOREIGN KEY (embedding_model_config_id) REFERENCES model_config (id),
    CONSTRAINT uk_knowledge_base_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX idx_knowledge_base_tenant_id ON knowledge_base (tenant_id);
CREATE INDEX idx_knowledge_base_embedding_model_config_id ON knowledge_base (embedding_model_config_id);
CREATE INDEX idx_knowledge_base_enabled ON knowledge_base (enabled);

-- 知识库文档表：记录上传文件及其处理状态。
CREATE TABLE knowledge_document
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT        NOT NULL,
    knowledge_base_id  BIGINT        NOT NULL,
    file_name          VARCHAR(255)  NOT NULL,
    content_type       VARCHAR(128),
    file_size          BIGINT        NOT NULL,
    storage_bucket     VARCHAR(128)  NOT NULL,
    storage_object_key VARCHAR(512)  NOT NULL,
    status             VARCHAR(32)   NOT NULL,
    chunk_count        INTEGER       NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_knowledge_document_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_knowledge_document_knowledge_base FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_base (id)
);

CREATE INDEX idx_knowledge_document_tenant_id ON knowledge_document (tenant_id);
CREATE INDEX idx_knowledge_document_knowledge_base_id ON knowledge_document (knowledge_base_id);
CREATE INDEX idx_knowledge_document_status ON knowledge_document (status);

-- 知识片段表：保存切片文本和向量，MVP 固定使用 1536 维向量。
CREATE TABLE knowledge_chunk
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT         NOT NULL,
    knowledge_base_id BIGINT         NOT NULL,
    document_id       BIGINT         NOT NULL,
    chunk_index       INTEGER        NOT NULL,
    content           TEXT           NOT NULL,
    embedding         VECTOR(1536)   NOT NULL,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_knowledge_chunk_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_knowledge_chunk_knowledge_base FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_base (id),
    CONSTRAINT fk_knowledge_chunk_document FOREIGN KEY (document_id) REFERENCES knowledge_document (id),
    CONSTRAINT uk_knowledge_chunk_document_index UNIQUE (document_id, chunk_index)
);

CREATE INDEX idx_knowledge_chunk_tenant_id ON knowledge_chunk (tenant_id);
CREATE INDEX idx_knowledge_chunk_knowledge_base_id ON knowledge_chunk (knowledge_base_id);
CREATE INDEX idx_knowledge_chunk_document_id ON knowledge_chunk (document_id);
CREATE INDEX idx_knowledge_chunk_embedding_cosine ON knowledge_chunk USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- Agent 增加可选的知识库绑定，MVP 一个 Agent 只绑定一个知识库。
ALTER TABLE agent
    ADD COLUMN knowledge_base_id BIGINT,
    ADD CONSTRAINT fk_agent_knowledge_base FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_base (id);

CREATE INDEX idx_agent_knowledge_base_id ON agent (knowledge_base_id);
