-- MCP Server：保存租户下接入的 MCP 服务端配置。
CREATE TABLE mcp_server
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT        NOT NULL,
    name           VARCHAR(128)  NOT NULL,
    description    VARCHAR(512),
    base_url       VARCHAR(512)  NOT NULL,
    transport_type VARCHAR(32)   NOT NULL,
    credential_id  BIGINT,
    enabled        BOOLEAN       NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMPTZ,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_mcp_server_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_mcp_server_credential FOREIGN KEY (credential_id) REFERENCES credential (id),
    CONSTRAINT uk_mcp_server_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX idx_mcp_server_tenant_id ON mcp_server (tenant_id);
CREATE INDEX idx_mcp_server_credential_id ON mcp_server (credential_id);
CREATE INDEX idx_mcp_server_enabled ON mcp_server (enabled);

-- MCP Tool：保存某个 MCP Server 暴露出来的工具目录快照。
CREATE TABLE mcp_tool
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT        NOT NULL,
    server_id         BIGINT        NOT NULL,
    name              VARCHAR(128)  NOT NULL,
    description       VARCHAR(1000),
    input_schema_json TEXT,
    risk_level        VARCHAR(32)   NOT NULL,
    enabled           BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_mcp_tool_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_mcp_tool_server FOREIGN KEY (server_id) REFERENCES mcp_server (id),
    CONSTRAINT uk_mcp_tool_server_name UNIQUE (server_id, name)
);

CREATE INDEX idx_mcp_tool_tenant_id ON mcp_tool (tenant_id);
CREATE INDEX idx_mcp_tool_server_id ON mcp_tool (server_id);
CREATE INDEX idx_mcp_tool_enabled ON mcp_tool (enabled);

-- Agent MCP Tool 绑定：表示某个 Agent 当前可调用的工具集合。
CREATE TABLE agent_mcp_tool
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT        NOT NULL,
    agent_id   BIGINT        NOT NULL,
    tool_id    BIGINT        NOT NULL,
    enabled    BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_agent_mcp_tool_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_agent_mcp_tool_agent FOREIGN KEY (agent_id) REFERENCES agent (id),
    CONSTRAINT fk_agent_mcp_tool_tool FOREIGN KEY (tool_id) REFERENCES mcp_tool (id),
    CONSTRAINT uk_agent_mcp_tool_agent_tool UNIQUE (agent_id, tool_id)
);

CREATE INDEX idx_agent_mcp_tool_tenant_id ON agent_mcp_tool (tenant_id);
CREATE INDEX idx_agent_mcp_tool_agent_id ON agent_mcp_tool (agent_id);
CREATE INDEX idx_agent_mcp_tool_tool_id ON agent_mcp_tool (tool_id);
CREATE INDEX idx_agent_mcp_tool_enabled ON agent_mcp_tool (enabled);
