-- MCP Tool 调用日志：记录聊天过程中触发的工具调用结果，便于审计与排障。
CREATE TABLE mcp_tool_call_log
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT        NOT NULL,
    user_id          BIGINT        NOT NULL,
    agent_id         BIGINT        NOT NULL,
    session_id       BIGINT        NOT NULL,
    user_message_id  BIGINT        NOT NULL,
    server_id        BIGINT        NOT NULL,
    tool_id          BIGINT        NOT NULL,
    tool_call_id     VARCHAR(128),
    tool_name        VARCHAR(128)  NOT NULL,
    status           VARCHAR(32)   NOT NULL,
    latency_ms       BIGINT,
    request_payload  TEXT,
    response_payload TEXT,
    error_code       VARCHAR(64),
    error_message    VARCHAR(1000),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_mcp_tool_call_log_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_mcp_tool_call_log_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_mcp_tool_call_log_agent FOREIGN KEY (agent_id) REFERENCES agent (id),
    CONSTRAINT fk_mcp_tool_call_log_session FOREIGN KEY (session_id) REFERENCES chat_session (id),
    CONSTRAINT fk_mcp_tool_call_log_user_message FOREIGN KEY (user_message_id) REFERENCES chat_message (id),
    CONSTRAINT fk_mcp_tool_call_log_server FOREIGN KEY (server_id) REFERENCES mcp_server (id),
    CONSTRAINT fk_mcp_tool_call_log_tool FOREIGN KEY (tool_id) REFERENCES mcp_tool (id)
);

CREATE INDEX idx_mcp_tool_call_log_tenant_id ON mcp_tool_call_log (tenant_id);
CREATE INDEX idx_mcp_tool_call_log_session_id ON mcp_tool_call_log (session_id);
CREATE INDEX idx_mcp_tool_call_log_tool_id ON mcp_tool_call_log (tool_id);
CREATE INDEX idx_mcp_tool_call_log_status ON mcp_tool_call_log (status);
CREATE INDEX idx_mcp_tool_call_log_created_at ON mcp_tool_call_log (created_at DESC);
